# Numpy Basics
> A quick walk through vector and matrix multiplication with Numpy.

- toc: true 
- badges: true
#- title: Numpy Basics
- hide: false
- comments: true
- author: Timothy L.J. Stewart
- image: images/numpy.png
- tags: [Python, Numpy, Matrix, Vector]
- permalink: /:title
- categories: [Python, Numpy, Matrix, Vector]



In [1]:
import numpy as np
from pprint import pprint
import matplotlib.pyplot as plt
# inner product = dot product       = a.T*b (Transpose here is only for distinction, np.dot() does not automagically Transpose, np.dot() expects proper dimensions for matrix math)
# outer product                     = a*b.T
# hadamard product = element-wise   = a*b

# a*b does a hadamard product
# dot(av,bv) of vectors does a hadamard product
# dot(am,bm) of matrix does matrix multiplication

# inner product = dot product (1*2)+(1*2)+(1*2)=6
a = np.array([1,1,1]) #this is not a column or row vector
b = np.array([2,2,2]) #this is not a column or row vector
print(f"\n(1)\na and b shape: {a.shape} -->  dot(a,b) = \n{np.dot(a,b)}")



(1)
a and b shape: (3,) -->  dot(a,b) = 
6


In [18]:

ac = np.array([ [1],
                [1],
                [1]]) 
bc = np.array( [[3],
                [2],
                [2]]) 
print(f"\n(2)\nar and bc shape: {ac.shape} {bc.shape} -->  \ndot(ac.T,bc) = \n{np.dot(ac.T,bc)} \ndot(bc.T,ac) = \n{np.dot(bc.T,ac)}")



(2)
ar and bc shape: (3, 1) (3, 1) -->  
dot(ac.T,bc) = 
[[7]] 
dot(bc.T,ac) = 
[[7]]


In [3]:

# One way to force a row or column vector is to use double bracket [[]]
# where [[0],  is a 2x1 column vector
#        [0]]
# and [[0,0]] is a 1x2 row vector

ar = np.array([[1,1,1 ]]) 
bc = np.array( [[3],
                [2],
                [2]]) 
print(f"\n(3)\nar and bc shape: {ar.shape} {bc.shape} -->  \ndot(ar,bc) = \n{np.dot(ar,bc)} \ndot(bc,ar) = \n{np.dot(bc,ar)}")




(3)
ar and bc shape: (1, 3) (3, 1) -->  
dot(ar,bc) = 
[[7]] 
dot(bc,ar) = 
[[3 3 3]
 [2 2 2]
 [2 2 2]]


In [17]:

ar = np.array([[1,1],
               [1,1]]) 
bc = np.array( [[1, 3],
                [2, 2]
                ]) 
print(f"ar and bc shape: {ar.shape} {bc.shape} -->  \ndot(ar,bc) = \n{np.dot(ar,bc)} \ndot(bc,ar) = \n{np.dot(bc,ar)} \n ar*bc = \n{ar*bc}")


ar and bc shape: (2, 2) (2, 2) -->  
dot(ar,bc) = 
[[3 5]
 [3 5]] 
dot(bc,ar) = 
[[4 4]
 [4 4]] 
 ar*bc = 
[[1 3]
 [2 2]]


## Wrong Dimensions

In [ ]:

# Wrong Dimensions
am = np.array([[1,1,1,1]]) #this is not a column or row vector
bm = np.array( [[2],
                [2],
                [2]]) #this is not a column or row vector
print(f"ar and bc shape: {am.shape} {bm.shape} -->  dot(a,b) = {np.dot(am,bm)}")